[build]
    publish = "dist/spa"
    #command = "npm install @quasar/app && quasar build"
    #command = "quasar build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
